// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --linked > packages/sdk/src/types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      cards: {
        Row: {
          age_max: number | null
          age_min: number | null
          answer_text: string | null
          bloom_level: string | null
          created_at: string
          deck_id: number
          difficulty: string | null
          id: number
          is_active: boolean
          language_code: string
          learning_objective: string | null
          prompt_text: string
          title: string | null
          updated_at: string
        }
        Insert: {
          age_max?: number | null
          age_min?: number | null
          answer_text?: string | null
          bloom_level?: string | null
          created_at?: string
          deck_id: number
          difficulty?: string | null
          id?: number
          is_active?: boolean
          language_code?: string
          learning_objective?: string | null
          prompt_text: string
          title?: string | null
          updated_at?: string
        }
        Update: {
          age_max?: number | null
          age_min?: number | null
          answer_text?: string | null
          bloom_level?: string | null
          created_at?: string
          deck_id?: number
          difficulty?: string | null
          id?: number
          is_active?: boolean
          language_code?: string
          learning_objective?: string | null
          prompt_text?: string
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cards_deck_id_fkey"
            columns: ["deck_id"]
            isOneToOne: false
            referencedRelation: "decks"
            referencedColumns: ["id"]
          }
        ]
      }
      card_media: {
        Row: {
          card_id: number
          media_asset_id: number
          role: string
          sort_order: number
        }
        Insert: {
          card_id: number
          media_asset_id: number
          role?: string
          sort_order?: number
        }
        Update: {
          card_id?: number
          media_asset_id?: number
          role?: string
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "card_media_card_id_fkey"
            columns: ["card_id"]
            isOneToOne: false
            referencedRelation: "cards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "card_media_media_asset_id_fkey"
            columns: ["media_asset_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          }
        ]
      }
      card_regions: {
        Row: {
          card_id: number
          coords: Json
          created_at: string
          id: number
          is_correct: boolean
          label: string | null
          media_asset_id: number
          shape: string | null
          sort_order: number
        }
        Insert: {
          card_id: number
          coords: Json
          created_at?: string
          id?: number
          is_correct?: boolean
          label?: string | null
          media_asset_id: number
          shape?: string | null
          sort_order?: number
        }
        Update: {
          card_id?: number
          coords?: Json
          created_at?: string
          id?: number
          is_correct?: boolean
          label?: string | null
          media_asset_id?: number
          shape?: string | null
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "card_regions_card_id_fkey"
            columns: ["card_id"]
            isOneToOne: false
            referencedRelation: "cards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "card_regions_media_asset_id_fkey"
            columns: ["media_asset_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          }
        ]
      }
      card_standards: {
        Row: {
          card_id: number
          standard_id: number
        }
        Insert: {
          card_id: number
          standard_id: number
        }
        Update: {
          card_id?: number
          standard_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "card_standards_card_id_fkey"
            columns: ["card_id"]
            isOneToOne: false
            referencedRelation: "cards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "card_standards_standard_id_fkey"
            columns: ["standard_id"]
            isOneToOne: false
            referencedRelation: "standards"
            referencedColumns: ["id"]
          }
        ]
      }
      card_tags: {
        Row: {
          card_id: number
          tag_id: number
        }
        Insert: {
          card_id: number
          tag_id: number
        }
        Update: {
          card_id?: number
          tag_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "card_tags_card_id_fkey"
            columns: ["card_id"]
            isOneToOne: false
            referencedRelation: "cards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "card_tags_tag_id_fkey"
            columns: ["tag_id"]
            isOneToOne: false
            referencedRelation: "tags"
            referencedColumns: ["id"]
          }
        ]
      }
      card_topics: {
        Row: {
          card_id: number
          topic_id: number
        }
        Insert: {
          card_id: number
          topic_id: number
        }
        Update: {
          card_id?: number
          topic_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "card_topics_card_id_fkey"
            columns: ["card_id"]
            isOneToOne: false
            referencedRelation: "cards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "card_topics_topic_id_fkey"
            columns: ["topic_id"]
            isOneToOne: false
            referencedRelation: "topics"
            referencedColumns: ["id"]
          }
        ]
      }
      deck_grade_levels: {
        Row: {
          deck_id: number
          grade_level_id: number
        }
        Insert: {
          deck_id: number
          grade_level_id: number
        }
        Update: {
          deck_id?: number
          grade_level_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "deck_grade_levels_deck_id_fkey"
            columns: ["deck_id"]
            isOneToOne: false
            referencedRelation: "decks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deck_grade_levels_grade_level_id_fkey"
            columns: ["grade_level_id"]
            isOneToOne: false
            referencedRelation: "grade_levels"
            referencedColumns: ["id"]
          }
        ]
      }
      deck_standards: {
        Row: {
          deck_id: number
          standard_id: number
        }
        Insert: {
          deck_id: number
          standard_id: number
        }
        Update: {
          deck_id?: number
          standard_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "deck_standards_deck_id_fkey"
            columns: ["deck_id"]
            isOneToOne: false
            referencedRelation: "decks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deck_standards_standard_id_fkey"
            columns: ["standard_id"]
            isOneToOne: false
            referencedRelation: "standards"
            referencedColumns: ["id"]
          }
        ]
      }
      deck_subjects: {
        Row: {
          deck_id: number
          subject_id: number
        }
        Insert: {
          deck_id: number
          subject_id: number
        }
        Update: {
          deck_id?: number
          subject_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "deck_subjects_deck_id_fkey"
            columns: ["deck_id"]
            isOneToOne: false
            referencedRelation: "decks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deck_subjects_subject_id_fkey"
            columns: ["subject_id"]
            isOneToOne: false
            referencedRelation: "subjects"
            referencedColumns: ["id"]
          }
        ]
      }
      deck_tags: {
        Row: {
          deck_id: number
          tag_id: number
        }
        Insert: {
          deck_id: number
          tag_id: number
        }
        Update: {
          deck_id?: number
          tag_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "deck_tags_deck_id_fkey"
            columns: ["deck_id"]
            isOneToOne: false
            referencedRelation: "decks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deck_tags_tag_id_fkey"
            columns: ["tag_id"]
            isOneToOne: false
            referencedRelation: "tags"
            referencedColumns: ["id"]
          }
        ]
      }
      deck_topics: {
        Row: {
          deck_id: number
          topic_id: number
        }
        Insert: {
          deck_id: number
          topic_id: number
        }
        Update: {
          deck_id?: number
          topic_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "deck_topics_deck_id_fkey"
            columns: ["deck_id"]
            isOneToOne: false
            referencedRelation: "decks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deck_topics_topic_id_fkey"
            columns: ["topic_id"]
            isOneToOne: false
            referencedRelation: "topics"
            referencedColumns: ["id"]
          }
        ]
      }
      decks: {
        Row: {
          created_at: string
          default_bloom_level: string | null
          default_difficulty: string | null
          description: string | null
          id: number
          language_code: string
          owner: string | null
          title: string
          updated_at: string
          visibility: string
        }
        Insert: {
          created_at?: string
          default_bloom_level?: string | null
          default_difficulty?: string | null
          description?: string | null
          id?: number
          language_code?: string
          owner: string | null
          title: string
          updated_at?: string
          visibility?: string
        }
        Update: {
          created_at?: string
          default_bloom_level?: string | null
          default_difficulty?: string | null
          description?: string | null
          id?: number
          language_code?: string
          owner?: string | null
          title?: string
          updated_at?: string
          visibility?: string
        }
        Relationships: [
          {
            foreignKeyName: "decks_owner_fkey"
            columns: ["owner"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      grade_levels: {
        Row: {
          code: string
          created_at: string
          id: number
          label: string
          level_type: string
          parent_id: number | null
          sort_order: number
        }
        Insert: {
          code: string
          created_at?: string
          id?: number
          label: string
          level_type: string
          parent_id?: number | null
          sort_order?: number
        }
        Update: {
          code?: string
          created_at?: string
          id?: number
          label?: string
          level_type?: string
          parent_id?: number | null
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "grade_levels_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "grade_levels"
            referencedColumns: ["id"]
          }
        ]
      }
      ingest_files: {
        Row: {
          created_at: string
          id: number
          meta: Json | null
          mime_type: string
          owner: string
          source: string
          storage_path: string
        }
        Insert: {
          created_at?: string
          id?: number
          meta?: Json | null
          mime_type: string
          owner: string
          source?: string
          storage_path: string
        }
        Update: {
          created_at?: string
          id?: number
          meta?: Json | null
          mime_type?: string
          owner?: string
          source?: string
          storage_path?: string
        }
        Relationships: [
          {
            foreignKeyName: "ingest_files_owner_fkey"
            columns: ["owner"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      jobs: {
        Row: {
          created_at: string
          created_by: string | null
          error: string | null
          id: number
          input: Json
          output: Json | null
          status: string
          type: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          error?: string | null
          id?: number
          input: Json
          output?: Json | null
          status?: string
          type: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          error?: string | null
          id?: number
          input?: Json
          output?: Json | null
          status?: string
          type?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "jobs_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      media_assets: {
        Row: {
          alt_text: string | null
          captions_path: string | null
          created_at: string
          duration_seconds: number | null
          height_px: number | null
          id: number
          license: string
          mime_type: string
          owner: string
          source_url: string | null
          storage_path: string
          transcript_path: string | null
          type: string
          width_px: number | null
        }
        Insert: {
          alt_text?: string | null
          captions_path?: string | null
          created_at?: string
          duration_seconds?: number | null
          height_px?: number | null
          id?: number
          license?: string
          mime_type: string
          owner: string
          source_url?: string | null
          storage_path: string
          transcript_path?: string | null
          type: string
          width_px?: number | null
        }
        Update: {
          alt_text?: string | null
          captions_path?: string | null
          created_at?: string
          duration_seconds?: number | null
          height_px?: number | null
          id?: number
          license?: string
          mime_type?: string
          owner?: string
          source_url?: string | null
          storage_path?: string
          transcript_path?: string | null
          type?: string
          width_px?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "media_assets_owner_fkey"
            columns: ["owner"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      quiz_attempt_answers: {
        Row: {
          attempt_id: number
          id: number
          is_correct: boolean | null
          quiz_item_id: number
          response_json: Json
          score_awarded: number | null
          time_taken_ms: number | null
        }
        Insert: {
          attempt_id: number
          id?: number
          is_correct?: boolean | null
          quiz_item_id: number
          response_json: Json
          score_awarded?: number | null
          time_taken_ms?: number | null
        }
        Update: {
          attempt_id?: number
          id?: number
          is_correct?: boolean | null
          quiz_item_id?: number
          response_json?: Json
          score_awarded?: number | null
          time_taken_ms?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "quiz_attempt_answers_attempt_id_fkey"
            columns: ["attempt_id"]
            isOneToOne: false
            referencedRelation: "quiz_attempts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quiz_attempt_answers_quiz_item_id_fkey"
            columns: ["quiz_item_id"]
            isOneToOne: false
            referencedRelation: "quiz_items"
            referencedColumns: ["id"]
          }
        ]
      }
      quiz_attempts: {
        Row: {
          details_json: Json | null
          id: number
          passed: boolean | null
          quiz_id: number
          score_pct: number | null
          score_raw: number | null
          started_at: string
          submitted_at: string | null
          user_id: string
        }
        Insert: {
          details_json?: Json | null
          id?: number
          passed?: boolean | null
          quiz_id: number
          score_pct?: number | null
          score_raw?: number | null
          started_at?: string
          submitted_at?: string | null
          user_id: string
        }
        Update: {
          details_json?: Json | null
          id?: number
          passed?: boolean | null
          quiz_id?: number
          score_pct?: number | null
          score_raw?: number | null
          started_at?: string
          submitted_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "quiz_attempts_quiz_id_fkey"
            columns: ["quiz_id"]
            isOneToOne: false
            referencedRelation: "quizzes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quiz_attempts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      quiz_blueprints: {
        Row: {
          constraints_json: Json
          created_at: string
          deck_id: number | null
          id: number
          name: string
          owner: string | null
        }
        Insert: {
          constraints_json: Json
          created_at?: string
          deck_id?: number | null
          id?: number
          name: string
          owner: string | null
        }
        Update: {
          constraints_json?: Json
          created_at?: string
          deck_id?: number | null
          id?: number
          name?: string
          owner?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "quiz_blueprints_deck_id_fkey"
            columns: ["deck_id"]
            isOneToOne: false
            referencedRelation: "decks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quiz_blueprints_owner_fkey"
            columns: ["owner"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      quiz_items: {
        Row: {
          id: number
          item_type: string
          media_snapshot: Json | null
          metadata_json: Json | null
          options_json: Json | null
          origin_card_id: number | null
          quiz_id: number
          scoring_json: Json
          sort_order: number
          stem: string
        }
        Insert: {
          id?: number
          item_type: string
          media_snapshot?: Json | null
          metadata_json?: Json | null
          options_json?: Json | null
          origin_card_id?: number | null
          quiz_id: number
          scoring_json: Json
          sort_order?: number
          stem: string
        }
        Update: {
          id?: number
          item_type?: string
          media_snapshot?: Json | null
          metadata_json?: Json | null
          options_json?: Json | null
          origin_card_id?: number | null
          quiz_id?: number
          scoring_json?: Json
          sort_order?: number
          stem?: string
        }
        Relationships: [
          {
            foreignKeyName: "quiz_items_origin_card_id_fkey"
            columns: ["origin_card_id"]
            isOneToOne: false
            referencedRelation: "cards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quiz_items_quiz_id_fkey"
            columns: ["quiz_id"]
            isOneToOne: false
            referencedRelation: "quizzes"
            referencedColumns: ["id"]
          }
        ]
      }
      quizzes: {
        Row: {
          blueprint_id: number | null
          created_at: string
          deck_id: number | null
          id: number
          mode: string | null
          owner: string | null
          settings_json: Json | null
          time_limit_seconds: number | null
          title: string
        }
        Insert: {
          blueprint_id?: number | null
          created_at?: string
          deck_id?: number | null
          id?: number
          mode?: string | null
          owner: string | null
          settings_json?: Json | null
          time_limit_seconds?: number | null
          title: string
        }
        Update: {
          blueprint_id?: number | null
          created_at?: string
          deck_id?: number | null
          id?: number
          mode?: string | null
          owner?: string | null
          settings_json?: Json | null
          time_limit_seconds?: number | null
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "quizzes_blueprint_id_fkey"
            columns: ["blueprint_id"]
            isOneToOne: false
            referencedRelation: "quiz_blueprints"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quizzes_deck_id_fkey"
            columns: ["deck_id"]
            isOneToOne: false
            referencedRelation: "decks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quizzes_owner_fkey"
            columns: ["owner"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      standards: {
        Row: {
          code: string
          created_at: string
          description: string
          framework: string
          id: number
          jurisdiction: string | null
        }
        Insert: {
          code: string
          created_at?: string
          description: string
          framework: string
          id?: number
          jurisdiction?: string | null
        }
        Update: {
          code?: string
          created_at?: string
          description?: string
          framework?: string
          id?: number
          jurisdiction?: string | null
        }
        Relationships: []
      }
      subjects: {
        Row: {
          created_at: string
          id: number
          name: string
          parent_id: number | null
          path: string
          slug: string
          sort_order: number
        }
        Insert: {
          created_at?: string
          id?: number
          name: string
          parent_id?: number | null
          path: string
          slug: string
          sort_order?: number
        }
        Update: {
          created_at?: string
          id?: number
          name?: string
          parent_id?: number | null
          path?: string
          slug?: string
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "subjects_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "subjects"
            referencedColumns: ["id"]
          }
        ]
      }
      tags: {
        Row: {
          color: string
          created_at: string
          id: number
          name: string
          slug: string
        }
        Insert: {
          color?: string
          created_at?: string
          id?: number
          name: string
          slug: string
        }
        Update: {
          color?: string
          created_at?: string
          id?: number
          name?: string
          slug?: string
        }
        Relationships: []
      }
      topics: {
        Row: {
          created_at: string
          id: number
          name: string
          parent_id: number | null
          path: string
          slug: string
          sort_order: number
          subject_id: number
        }
        Insert: {
          created_at?: string
          id?: number
          name: string
          parent_id?: number | null
          path: string
          slug: string
          sort_order?: number
          subject_id: number
        }
        Update: {
          created_at?: string
          id?: number
          name?: string
          parent_id?: number | null
          path?: string
          slug?: string
          sort_order?: number
          subject_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "topics_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "topics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "topics_subject_id_fkey"
            columns: ["subject_id"]
            isOneToOne: false
            referencedRelation: "subjects"
            referencedColumns: ["id"]
          }
        ]
      }
      users: {
        Row: {
          avatar_url: string | null
          created_at: string
          display_name: string | null
          email: string | null
          id: string
          language_preference: string
          timezone: string
          username: string | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          email?: string | null
          id: string
          language_preference?: string
          timezone?: string
          username?: string | null
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          email?: string | null
          id?: string
          language_preference?: string
          timezone?: string
          username?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "users_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
